const smartPhonesProducts = [
	{
		id: "1",
		price: "329",
		isNewProduct: true,
		link: "www.realme.co.uk",
		title: "GT Master Edition",
		subtitle: "Snapdragon 778G 5G Processor | 120Hz Super AMOLED",
		productImage: "/images/productImages/1634037855775.png",
		backgroundImage: "",
	},
	{
		id: "2",
		price: "199",
		isNewProduct: true,
		link: "www.realme.co.uk",
		title: "realme 8 5G",
		subtitle: "Dimensity 700 5G Processor | 90Hz Ultra Smooth Display",
		productImage: "/images/productImages/1620815878085.png",
		backgroundImage: "",
	},
	{
		id: "3",
		price: "199",
		isNewProduct: false,
		link: "www.realme.co.uk",
		title: "realme 8",
		subtitle: "64MP AI Quad Camera | Helio G95 Gaming Processor",
		productImage: "/images/productImages/1619510447064.png",
		backgroundImage: "",
	},
	{
		id: "4",
		price: "279",
		isNewProduct: false,
		link: "www.realme.co.uk",
		title: "realme 8 Pro",
		subtitle: "108MP Ultra Quad Camera | 50W SuperDart Charge",
		productImage: "/images/productImages/1616130586852.png",
		backgroundImage: "",
	},
	{
		id: "5",
		price: "279",
		isNewProduct: false,
		link: "www.realme.co.uk",
		title: "realme 7 Pro",
		subtitle: "65W Charging Evolution",
		productImage: "/images/productImages/1603382475348.jpg",
		backgroundImage: "",
	},
	{
		id: "6",
		price: "109",
		isNewProduct: false,
		link: "www.realme.co.uk",
		title: "realme C21",
		subtitle: "Triple camera. Real quality. | 5000mAh Massive Battery | 13M...",
		productImage: "/images/productImages/1619505327029.png",
		backgroundImage: "",
	},
];

const accessoriesProducts = [
	{
		id: "1",
		price: "69.99",
		isNewProduct: true,
		link: "www.realme.co.uk",
		title: "realme watch 2 pro",
		subtitle: "Big Display. Pro Sports.",
		productImage: "/images/productImages/1615884298148.png",
		backgroundImage: "/images/otherImages/1626338409118.jpg",
	},
	{
		id: "2",
		price: "49.99",
		isNewProduct: true,
		link: "www.realme.co.uk",
		title: "realme watch 2",
		subtitle: "Smart. Sporty. Always On.",
		productImage: "/images/productImages/1615892685998.png",
		backgroundImage: "/images/otherImages/1626338418290.jpg",
	},
	{
		id: "3",
		price: "27.99",
		isNewProduct: true,
		link: "www.realme.co.uk",
		title: "realme Buds Q2",
		subtitle: "Quite clear, long-lasting",
		productImage: "/images/productImages/1593770987632.jpg",
		backgroundImage: "",
	},
	{
		id: "4",
		price: "37.99",
		isNewProduct: false,
		link: "www.realme.co.uk",
		title: " realme Smart Camera 360",
		subtitle: "360 Vision. 24/7 Protection",
		productImage: "/images/productImages/1607070370773.jpg",
		backgroundImage: "",
	},
];

const limitTimeProducts = [
	{
		id: "1",
		price: "699",
		discountPrice: "449",
		link: "www.realme.co.uk",
		image: "/images/productImages/1588462321861.jpg",
		title: "realme X50 Pro 5G",
		subtitle: "RUST RED UK PLUG 12GB+256GB",
	},
	{
		id: "2",
		price: "699",
		discountPrice: "449",
		link: "www.realme.co.uk",
		image: "/images/productImages/1594595165858.jpg",
		title: "realme X50 Pro 5G",
		subtitle: "MOSS GREEN UK PLUG 12GB+256GB",
	},
	{
		id: "3",
		price: "229",
		discountPrice: "229",
		link: "www.realme.co.uk",
		image: "/images/productImages/1579143987209.jpg",
		title: "realme X2",
		subtitle: "PEARL WHITE UK PLUG 12GB+256GB",
	},
	{
		id: "4",
		price: "39.99",
		discountPrice: "29.99",
		link: "www.realme.co.uk",
		image: "/images/productImages/1590427823443.jpg",
		title: "realme Buds Air Pro",
		subtitle: "Soul While",
	},
];

const otherProducts = [
	{
		id: "1",
		price: "46.99",
		link: "www.realme.co.uk",
		image: "/images/productImages/1615884298148.png",
		title: "realme Buds Air 2",
		subtitle: "Noise Off, realme On.",
	},
	{
		id: "2",
		price: "79.99",
		link: "www.realme.co.uk",
		image: "/images/productImages/1615892685998.png",
		title: "realme Buds Air Pro",
		subtitle: "Tune Out the Noise",
	},
	{
		id: "3",
		price: "119",
		link: "www.realme.co.uk",
		image: "/images/productImages/1615876911131.png",
		title: "realme Watch 2 Pro",
		subtitle: "The stylish new Pro",
	},
	{
		id: "4",
		price: "34.99",
		link: "www.realme.co.uk",
		image: "/images/productImages/1607080800022.jpg",
		title: "realme Buds Wireless Pro",
		subtitle: "Noise Off. Music On",
	},
];

export {
	otherProducts,
	accessoriesProducts,
	smartPhonesProducts,
	limitTimeProducts,
};
